apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-deployment
          image: 145023126233.dkr.ecr.us-east-1.amazonaws.com/app-lanchonete:2.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          startupProbe:
            httpGet:
              path: /startup
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 6
            failureThreshold: 25
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 6
            failureThreshold: 25
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 6
            failureThreshold: 25
