server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: tech-challenge
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MySQL8Dialect"
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,startup"
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  startup:
    enabled: true
  info:
    enabled: true
  security:
    enabled: false

# Configuração do H2 para rodar local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
